---
title: "t-test-loop"
output: html_document
date: "2022-10-19"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(TOSTER)
```

```{r}
alphas = c(0.05, 0.01, 0.005, 0.001, 0.0005)
l_a = length(alphas) 

n = seq(5, 5000, length.out = 1000)
l_n = length(n)
p_values <- array(NA, dim = l_n)

repeats = 1000
dat = list()
```


```{r, eval = FALSE}
##  
##  WARNING: lOOP TAKES SEVERAL MINUTES TO RUN
##

for (i in 1:l_a){
  
  dat[[i]] <-  replicate(repeats, expr = t.test.loop(n, p_values, alpha = alphas[i], break_loop = TRUE, get_pval = TRUE)) |>
    as.data.frame(row.names = NA) |> 
    rename_with(.cols = contains("V"), .fn =  ~ 1:repeats) |> 
    mutate(n = n*2, alpha = as.factor(alphas[i])) |>
    select(n, alpha, everything()) |>
    pivot_longer(cols = c(-n, -alpha),
                 values_to = "pval",
                 names_to = "set")

  dat
}


```


```{r, eval = FALSE}

# df <- dat |>
#   bind_rows() |>
#   group_by(n, alpha)  |>
#   na.omit() |>
#   summarise(count = n(),
#             prop = count /repeats,
#             .groups = "drop")
# 
# 
# 
# head(df)

# write_csv(x= df, file = "../my-scripts/p_values_alphas_summary.csv")
# write_csv(x= as.data.frame(dat), file = "../my-scripts/p_values_alphas.csv")
```

```{r, fig.height=8}
df <- read_csv("p_values_alphas_summary.csv", col_types = "ifi?")


df |> 
  ggplot(aes(x = n, y = pval, colour = alpha))+
  geom_line(aes(x = n, y = 1 - prop), size = 1.2, alpha = 0.7)+
  scale_x_log10("N")+
  scale_y_continuous("Proportation of Null Hypothesis Rejections")+
  ggtitle("Sequential t-test of Same Population Results in False Positives")+
  theme_minimal()
```


```{r, eval=FALSE}
means = list()

for (i in 1:l_a){
  
 means[[i]] <-  replicate(repeats, expr = t.test.loop(n, p_values, alpha = alphas[i], break_loop = TRUE, get_pval = FALSE)) |>
  as.data.frame(row.names = NA) |> 
  rename_with(.cols = contains("V"), .fn =  ~ 1:repeats) |> 
  mutate(n = n*2, alpha = as.factor(alphas[i])) |> 
  select(n, alpha, everything()) |> 
  pivot_longer(cols = c(-n, -alpha),
               values_to = "diff",
               names_to = "set") 

 means
}
```

```{r, eval = FALSE}
mean_df <- means |>
  bind_rows() |>
  group_by(n, alpha)  |>
  na.omit()|> 
  mutate(mean = mean(abs(diff)), 
         sd = sd (abs(diff)))

 
# write_csv(x= mean_df, file = "../my-scripts/mean_diff_alpha_summary.csv")
# write_csv(x= as.data.frame(means), file = "../my-scripts/mean_diff_alpha.csv")

head(mean_df)
```

```{r, fig.height=8, message= F}

mean_df <- read_csv("mean_diff_alpha_summary.csv", col_types = "ifiddd")

mean_df |>
  filter(alpha == 0.05) |> 
  ggplot(aes(x = n, y = abs(diff)))+
  geom_point(size = 2, alpha = .2, colour = "blue")+
  geom_ribbon(aes(ymin = mean - (sd/2), ymax = mean + (sd/2)), alpha = .4, fill = "lightblue")+
  geom_line(aes(x = n, y = mean), size = 2, colour = "darkblue", alpha = .6)+
  theme_minimal()+
  scale_x_log10("Sample Size")+
  scale_y_continuous("Absolute Mean Difference")+
  ggtitle("Mean Difference of Significant results at different sample sizes (p < 0.05)")+
  coord_cartesian(expand = T)


```

```{r, fig.height= 8, fig.width= 13}
mean_df |> 
  ggplot(aes(x = n, y = abs(diff), colour = alpha))+
  geom_point(size = 2, alpha = .3)+
  geom_line(aes(y = mean), size = 2, alpha = .2)+
  geom_point(aes(y = mean), size = 1, alpha = .7)+
  theme_minimal()+
  scale_x_log10("Sample Size")+
  scale_y_continuous("Absolute Mean Difference")+
  ggtitle("Mean Difference of Significant results at different sample sizes (for different alphas)")
  # ggforce::facet_zoom(xlim = c(1000, 10000), ylim = c(0, 0.2))
```

```{r}
conf_int <- function(x, alpha){
  s = sd(x)
  mu = mean(x, na.rm = TRUE)
  n = length(!is.na(x))
  margin <- qt(1 - (alpha / 2),df = n - 1) * s / sqrt(n)
  
  return(c(mu+margin, mu-margin))
  
}

```


