---
title: "bayes-factors"
author: "Mark G"
date: "2022-11-07"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, fig.height = 8, fig.width = 10)
```

```{r}
library(BayesFactor)
library(tidyverse)
library(doParallel)
library(ggtext) 

doParallel::registerDoParallel(cores = parallel::detectCores()-2)

source(here::here("my-scripts", "R", "project_themes.R"))
base_size = 13
```


```{r}
n1 <- rnorm(100)
n2 <- rnorm(100)

t.test(n1, n2)
BayesFactor::ttestBF(n1, n2)
```


```{r}
# Testing posterior = TRUE output
# 
# bayes_test <- function(sample_size, mean_diff = 0, nullInterval = NULL, iterations){
#   
#   len_n <- length(sample_size)
# 
#   output <- foreach::foreach (s = 1:len_n, .combine = "rbind") %dopar%{
#     # generate sample
#     s1 = rnorm(sample_size[s], mean = 0, sd = 1)
#     s2 = rnorm(sample_size[s], mean = 0 + mean_diff, sd = 1)
#     
#     # t test between two samples
#     bf <- BayesFactor::ttestBF(s1, s2, nullInterval = nullInterval, posterior = T, iterations = iterations)
#     
#     # finding the mean diff
#     mean_diff <- mean(s1) - mean(s2)
#     
#     # combining output
#     cbind(sample_size[s], bf[,1], mean_diff) 
#     
#   }
#   
#   output |>
#     tibble::as_tibble(.name_repair = ~ c("n", "mean_diff", "real_mean_diff"))
# }


```

```{r}
# sample_size <- seq(5, 5000, 5)
# test <- bayes_test(sample_size = sample_size, iterations = 10000, nullInterval = c(-.1, .1))

```

```{r}
bf_ttest_fast_loop <- function(sample_size, mean_diff = 0, nullInterval = NULL, rscale = NULL){
  
  if(is.null(rscale)){
    rscale = "medium"
  }
  
  s1 <- s2 <- c()
  
  len_n <- length(sample_size)

  output <-  foreach::foreach (s = 1:len_n, .combine = "rbind") %dopar%{
    # generate sample
    s1 = c( s1, rnorm(5, mean = 0, sd = 1))
    s2 = c( s2, rnorm(5, mean = mean_diff, sd = 1))
    
    # t test between two samples
    bf <- BayesFactor::ttestBF(s1, s2, rscale = rscale, nullInterval = nullInterval)
    
    # finding the mean diff
    mean_diff <- mean(s1) - mean(s2)
    
    # combining output
    c(sample_size[s], as.vector(bf)[[1]],  mean_diff, rscale) 
    
  }
  
  output |> 
    tibble::as_tibble(.name_repair = ~ c("n", "bf", "mean_diff", "rscale"))
}
```

```{r, message=F}

sample_size <- seq(5,5000,5)

df <- bf_ttest_fast_loop(sample_size, mean_diff = 0)
```

```{r}
df |> 
  # filter(bf < 10000) |> 
  ggplot(aes(n, bf))+
  geom_point()
```


```{r,eval = FALSE, message=FALSE}
sample_size = seq(5,5000,5)

repeats = 1000

bf_ttest_df <- replicate(repeats, expr = bf_ttest_fast_loop(sample_size = sample_size, mean_diff = 0)) |>
    t() |> 
    tibble::as_tibble(.name_repair = ~ c("n", "bf", "mean_diff", "rscale")) |> 
    map_dfr(~unlist(.x))

bf_ttest_df_2 <- replicate(repeats, expr = bf_ttest_fast_loop(sample_size = sample_size, mean_diff = 0, rscale = "wide")) |>
    t() |> 
    tibble::as_tibble(.name_repair = ~ c("n", "bf", "mean_diff", "rscale")) |> 
    map_dfr(~unlist(.x))

bf_ttest_df_3 <- replicate(repeats, expr = bf_ttest_fast_loop(sample_size = sample_size, mean_diff = 0, rscale = "ultrawide")) |>
    t() |> 
    tibble::as_tibble(.name_repair = ~ c("n", "bf", "mean_diff", "rscale")) |> 
    map_dfr(~unlist(.x))
```



```{r}
bf_ttest_df |> 
  filter(bf < 1000) |> 
  ggplot()+
  geom_point(aes(n, bf), colour = "darkred")
  # geom_point(aes(n, 1/exp(1)^bf), colour = "darkblue", alpha = .1)
```


```{r}
here::i_am("./my-scripts/RMD/bayes-factor-testing.Rmd")
here::here()
```


```{r, eval = F}
bf_r_df <- bind_rows(bf_ttest_df, bf_ttest_df_2, bf_ttest_df_3)

# write_csv(bf_ttest_df, file =   here::here("./sim_data/bf_ttest_med.csv"))
# write_csv(bf_ttest_df_2, file = here::here("./sim_data/bf_ttest_wide.csv"))
# write_csv(bf_ttest_df_3, file = here::here("./sim_data/bf_ttest_ultwide.csv"))
# write_csv(bf_r_df, file = here::here("./sim_data/bf_ttest_df.csv"))
```


```{r}
bf_ttest_df <- read_csv(here::here("sim_data", "ch3_bayes", "bf_ttest_med.csv"))
bf_ttest_df_2 <- read_csv(here::here("sim_data", "ch3_bayes", "bf_ttest_wide.csv"))
bf_ttest_df_3 <- read_csv(here::here("sim_data", "ch3_bayes", "bf_ttest_ultwide.csv"))
bf_r_df <- read_csv(here::here("sim_data", "ch3_bayes", "bf_ttest_df.csv"))

```

```{r}
get_prop_for_bf <- function(df, ...){
  df |> 
    group_by(n, {{...}}) |> 
    mutate(h = if_else(bf > 3, 1, 0),
           h = if_else((bf <= 3 & bf >= 1/3), 0, h),
           h = if_else(bf < 1/3, -1, h), 
           prop_1 = 100*sum(h == 1)/ n(),
           prop_0 = 100*sum(h == -1)/ n()) |> 
    select(-h) |> 
    summarise(across(.cols = c("bf", "mean_diff", contains("prop_")),
                     .fns = list(mean = mean, sd = ~ sd(.x), mean_t = ~ mean(.x, trim = .05)),
                     .names = "{.col}_{.fn}"))|> 
    select(!c(prop_1_sd, prop_0_sd, prop_1_mean_t, prop_0_mean_t))
}

plot_prop_for_bf <- function(df){
  df |>
    ggplot(aes(n, bf))+
    geom_point(aes(colour = 1/bf < 3), alpha = 0.1, size = .5, show.legend = F)+
    theme_project_light()+
    scale_y_continuous("Bayes Factor", limits = c(0,5))+
    scale_colour_manual(values = c("darkred", "skyblue4"))
}


```

```{r}
bf_df <- bf_ttest_df |> 
  get_prop_for_bf() 

bf_df_2 <- bf_ttest_df_2 |> 
  get_prop_for_bf()

bf_df
bf_df_2
```

```{r}
bf_ttest_df |>
  plot_prop_for_bf()


```

```{r}
bf_df|> 
  ggplot(aes(x = n, y = bf_mean))+
  geom_point(alpha = .5, size = 2.5, fill = "skyblue4", shape = 21, stroke = NA)+
  # geom_point(aes(y = bf_mean_t), alpha = .8, size = .8, colour = "skyblue4")+
  scale_y_continuous(expression(paste("Bayes Factor ")(BF[10])), breaks = c(0, 0.3, 0.6, 0.9))+
  scale_x_continuous("Sample Size")+
  theme_project_light(base_size = base_size)+
  labs(title = "Mean Bayes Factor Across Sample Sizes from Bayesian T-tests")+
  theme(plot.title = element_markdown(lineheight = 1))+
  annotate("rect", ymin = 0, ymax = 0.3, xmin = 0, xmax = 5000, alpha = .3, fill = "skyblue3")+
  annotate("text", y = 0.3, x = 5000, label = "Supports Null Hypothesis", vjust = 1.1, hjust = 1, colour = "skyblue4", size = 6)+
  coord_cartesian(ylim = c(0, 1))

ggsave(filename = here::here("images", "ch3_bf_simple.png"), dpi = 360, width = 10, height = 8)
```

```{r}

colour1 = '#BDB9B7' # just to show how ggtext can work with variable names

bf_df |> 
  ggplot(aes(x= n))+
  geom_point(aes(y = prop_1_mean), colour = colour1, size = .5)+
  geom_point(aes(y = prop_0_mean), colour = "darkred", size = .5)+
  geom_point(aes(y = 100 - (prop_0_mean + prop_1_mean)), colour = "darkcyan", size = .5)+
  theme_project_light()+
  scale_y_continuous("Proportion of Tests (%)")+
  scale_x_continuous("Sample Size")+
  labs(title = glue::glue(
         "<b>1,000,000 Simulated Bayesian T-tests Showing Proportion of </b><br>Results which favour the
          <b><span style='color:#8B0000;'>Null</b><span>,
          <b><span style='color:{colour1};'>Alternative</b><span> and
          <b><span style='color:#008B8B;'>Neither</b><span>"))+
  theme(plot.title = element_markdown())



#ggplot2::luv_colours
#008B8Bblob:https://teams.microsoft.com/ddc483dd-9842-49e1-b74e-4532b0720735
```
```{r}
bf_r <- bf_r_df |> 
    group_by(n, rscale) |> 
    mutate(h = if_else(bf > 3, 1, 0),
           h = if_else((bf <= 3 & bf >= 1/3), 0, h),
           h = if_else(bf < 1/3, -1, h), 
           prop_1 = 100*sum(h == 1)/ n(),
           prop_0 = 100*sum(h == -1)/ n()) |> 
    select(-h) |> 
    summarise(across(.cols = c("bf", "mean_diff", contains("prop_")),
                     .fns = list(mean = mean, sd = ~ sd(.x), mean_t = ~ mean(.x, trim = .05)),
                     .names = "{.col}_{.fn}"), 
              .groups = "drop")|> 
    select(!c(prop_1_sd, prop_0_sd, prop_1_mean_t, prop_0_mean_t))

bf_r |> 
  ggplot(aes(x= n, colour = rscale))+
  geom_point(aes(y = prop_0_mean), size = .5)+
  theme_project_light()+
  scale_y_continuous("Proportion of Tests (%)")+
  scale_x_continuous("Sample Size")+
  labs(title = glue::glue(
         "1,000,000 Simulated Bayesian T-tests Showing Proportion of </b><br>Results which favour the Null"))+
  theme(plot.title = element_markdown())

bf_r |> 
  ggplot(aes(x= n, y = bf_mean, colour = rscale))+
  geom_point(alpha = .5, size = .8)+
  scale_y_log10("Bayes Factor")+
  scale_x_continuous("Sample Size")+
  theme_project_light()+
  labs(title =
         "<b>1,000,000 Simulated Bayesian T-tests Showing Mean Bayes Factor</b>")+
  theme(plot.title = element_markdown(lineheight = 1))
```



```{r}

# bf_df |> 
#   ggplot(aes(x = n, y = mean_diff_mean))+
#   geom_point()+
#   geom_ribbon(aes(ymax = mean_diff_mean + (mean_diff_sd / 2), ymin = mean_diff_mean - (mean_diff_sd / 2)), alpha = 0.2)+
#   theme_project_light()+
#   scale_y_continuous("Absolute Mean Difference")+
#   labs(title = "Absolute Mean Difference between Two Groups from 1,000,000 Bayesian T-Tests")
# 
# bf_df_2 |> 
#   ggplot(aes(x = n, y = mean_diff_mean))+
#   geom_point()+
#   geom_ribbon(aes(ymax = mean_diff_mean + (mean_diff_sd / 2), ymin = mean_diff_mean - (mean_diff_sd / 2)), alpha = 0.2)+
#   theme_project_light()+
#   scale_y_continuous("Mean Difference")+
#   labs(title = "Mean Difference between Two Groups from 1,000,000 Bayesian T-Tests")

```

