---
title: "Equivalance-testing"
output: html_document
date: "2022-10-13"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, 
                      fig.height = 8,
                      fig.width = 8 )
```

```{r}
library(tidyverse)
library(pwr)
library(TOSTER)
library(ggforce)

source(here::here("other-scripts", "optim_equiv_func.R")) # to get optim_equiv function
source(here::here("my-scripts","R","tost_loop_functions.R"))
source(here::here("my-scripts","R","project_themes.R"))
```

```{r, warning = FALSE, message=FALSE}

sample = c(25,50,100)
m = 0 # mean of both groups set to 100
d = c(1:100)/100 # smaller increments for smoother graph
sd = 1
alpha = 0.05
margin = 0.2

tost_pval <- get_pval_tost_loop(sample_vec = sample, 
                                row_vec = d, 
                                margin = margin, 
                                mean = m, 
                                sd = sd, 
                                alpha = alpha)

knitr::kable(x = head(tost_pval, n = 10))
```

```{r}
tost_pval_df <- tost_pval |> 
  tidy_tost_loop(diff_vec = d)

knitr::kable(x = head(tost_pval_df, n = 10))
```

```{r}
tost_pval_df |> 
  ggplot(aes(x = diff/sd, y = p, colour = n, linetype = t))+
  geom_line(size = 1.2, alpha = 0.7)+
  geom_hline(yintercept = 0.05)+
  ggtitle("TOST and t-test, p-value at different mean differences (SD = 10) at \nThree sample sizes (25,50,100)")+
  scale_x_continuous(name = "Cohen's d", breaks = seq(0, 10, .1))+
  # facet_grid(~ t)+
  theme_minimal()
```

```{r, message=FALSE}
sample = c(25,50, 100, 250, 500)
alpha = 0.05

tost_pval_2 <- get_pval_tost_loop(sample_vec = sample, 
                                row_vec = d, 
                                margin = margin, 
                                mean = m, 
                                sd = sd, 
                                alpha = alpha,
                                eqbound_type = "SMD")


knitr::kable(x = head(tost_pval_2, n = 10))
```

```{r}
tost_pval_2_df <- tost_pval_2 |> 
  tidy_tost_loop(diff_vec = d) |> 
  mutate(n = factor(n ,levels = sample))
```

```{r}
tost_pval_2_df |> 
  filter(t == "lower") |> 
  ggplot(aes(x = diff, y = p, colour = n))+
  geom_line(size = 1.2, alpha = 0.7)+
  geom_hline(yintercept = 0.05)+
  ggtitle("P-values from Various Mean Differences, with a Equivalence Margin of 0.2")+
  labs(caption = 
      "Remember that the upper and lower bounds are 0.2 Cohen's d and we assume the correlation is base, 
       this reflects a more theoretical experiment. We need both tests to return a p value less than alpha 
       for 'significant' equivalance.")+
  scale_y_continuous(limits = c(0,1))+
  scale_x_continuous(name = "Mean Difference")+
  theme_project_light()
```

```{r, message=FALSE}
sample = c(25,50, 100, 500, 1000)
margin = seq(0.05, 0.5, 0.05)

p_val_loop_dat = list()


# loop to get p values for different margins for different differences at different sample sizes
for(m in 1:length(margin)){
  
  p_val_loop_dat[[m]] <- get_pval_tost_loop(sample_vec = sample, 
                     row_vec = d, 
                     margin = margin[m], 
                     mean = mn , 
                     sd = sd, 
                     alpha = alpha, 
                     eqbound_type = "SMD") |> 
    tidy_tost_loop(diff_vec = d) |> 
    mutate("margin" = as.factor(margin[m]))

}

tost_pval_margins_df <- p_val_loop_dat |> 
  bind_rows()

  
head(tost_pval_margins_df)
```

```{r, fig.height=9, fig.width= 9}

tost_pval_margins_df |> 
  filter(t != "t") |> 
  ggplot(aes(x = diff, y = p, colour = margin))+
  # geom_point(alpha = 0.5, size = 1)+
  geom_line(alpha = 0.7, size = 1)+
  scale_x_continuous("Difference between Groups")+
  scale_y_continuous("p value")+
  facet_grid(cols = vars(t), rows = vars(factor(n, levels = sample)), scales = "free_x")+
  theme_project_light()+
  theme(legend.position = "top")

```

```{r, eval = FALSE}

result_3 <- array(NA, dim = c(length(d), 2*length(sample)))

for(s in 1:length(sample)){
  for(diff in 1:length(d)){
    n1 = rnorm(sample[s], mean = m, sd = sd)
    n2 = rnorm(sample[s], mean = m+d[diff], sd = sd)
    
    output <- optim_equiv(n1, n2, margin = .2)
    
    result_3[diff, 2*s-1] <- output[1] # tost
    result_3[diff, 2*s] <- output[2] # optim
  }
}

```

```{r, eval = FALSE}
result_tibble_3 <- result_3 |> 
  as_tibble() |> 
  rename(
    "tost_10a" = V1, "optim_10a" = V2,
    "tost_10b" = V3, "optim_10b" = V4,
    "tost_10c" = V5, "optim_10c" = V6,
    "tost_10d" = V7, "optim_10d" = V8,
    "tost_10e" = V9, "optim_10e" = V10, 
         # "tost_50" = V3, "optim_50" = V4,
         # "tost_100" = V5, "optim_100" = V6,
         ) |> 
  mutate(diff = d) |> 
  pivot_longer(cols = (-diff),
               names_to = "test", 
               values_to = "p") |> 
    mutate(n = str_extract(test, pattern = "[0-9]+"),
           t = str_extract(test, pattern = "[t_]*[a-z]+")
         )


```

```{r, eval = FALSE}
result_tibble_3 |> 
  ggplot(aes(x = diff, y = p, colour = t))+
  geom_point(size = 1.2, alpha = 0.4)+
  geom_hline(yintercept = 0.05)+
  theme_minimal()
```
