---
title: "confidence-intervals"
output: html_document
date: "2022-10-17"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,  fig.height = 8, fig.width = 10, dpi = 300)
```

```{r}
library(tidyverse)
library(TOSTER)

source(file = here::here("my-scripts/R", "tost_loop_functions.R"))
source(file = here::here("my-scripts/R", "t_test_loop_functions.R"))

## theme for the plots
source(here::here("my-scripts", "R", "project_themes.R"))
# set theme to project_theme
theme_set(theme_project_light())
```

## Chapter 2 - Sequential Testing and Basic Application of ROPEs

```{r, eval= TRUE}
seq_t_test_many_alphas_mean_break <- read_csv(file = here::here("./sim_data/seq_t_test_many_alphas_mean_break.csv"))
p_vals_tost_no_break <- read_csv(file = here::here("./sim_data/p_vals_tost_no_break.csv"))
p_vals_tost_break_logn <- read_csv(file = here::here("./sim_data/p_vals_tost_break_logn.csv"))
p_vals_tost_break_small_alpha <- read_csv(file = here::here("./sim_data/p_vals_tost_break_small_alpha.csv"))
p_vals_tost_break_one_sample <- read_csv(file = here::here("./sim_data/p_vals_tost_break_one_sample.csv"))

seq_t_test_many_alphas_rope <- read_csv(file = here::here("./sim_data/seq_t_test_many_alphas_rope.csv"))
seq_t_test_many_alphas_rope_1 <- read_csv(file = here::here("./sim_data/seq_t_test_many_alphas_rope_1.csv"))

seq_t_test_many_alphas_rope_m <- read_csv(file = here::here("./sim_data/seq_t_test_many_alphas_rope_m.csv"))
```

```{r}
n = seq(5, 5000, length.out = 1000)
l_n = length(n)

n_log <- 10^(seq(1,4,.01))
l_nlog = length(n_log)

alphas = c(0.05, 0.01, 0.005, 0.001, 0.0005)
l_a = length(alphas)

repeats = 1000
```

## Different sequential tests, with breaks, without breaks, different alphas, etc
```{r}
# I think this is unneed for the csv is in acceptable format and these functions do not produce nice dataframes

# seq_t_test_many_alphas_mean_break_df <- seq_t_test_many_alphas_mean_break |> 
#     summarise_t_test_loop(n = n, repeats = repeats)
# 
# p_vals_tost_break_small_alpha_df <- p_vals_tost_break_small_alpha |> 
#   summarise_t_test_loop(n = n, repeats = repeats)
# 
# p_vals_tost_break_logn_df <- p_vals_tost_break_logn |> 
#   summarise_t_test_loop(n = n_log, repeats = repeats)
# 
# p_vals_tost_no_break_df <- p_vals_tost_no_break |> 
#   summarise_t_test_loop(n = n, repeats = repeats)
# 
# p_vals_tost_break_one_sample_df <- p_vals_tost_break_one_sample |> 
#    summarise_t_test_loop(n = n, repeats = repeats)
```

## ROPE Sequential Test
```{r}
seq_t_test_many_alphas_rope_df <- seq_t_test_many_alphas_rope |> 
  group_by(alpha) |> 
  summarise(prop = cumsum(failed), 
            .groups = "drop") |> 
  mutate(n = as.integer(rep(n*2, times = l_a)))

seq_t_test_many_alphas_rope_1_df <- seq_t_test_many_alphas_rope_1 |> 
  group_by(alpha) |> 
  summarise(prop = cumsum(failed), 
            .groups = "drop") |> 
  mutate(n = as.integer(rep(n*2, times = l_a)))
```

```{r}
l_margins <- seq_t_test_many_alphas_rope_m |> 
  select(margin) |> 
  unique() |> 
  unlist() |> 
  length()

seq_t_test_many_alphas_rope_m_df <- seq_t_test_many_alphas_rope_m |> 
  group_by(margin) |> 
  summarise(prop = cumsum(failed), 
            .groups = "drop") |> 
  mutate(n = as.integer(rep(n*2, times = l_margins)))
```


```{r}
seq_t_test_many_alphas_mean_break |>
  group_by(alpha) |> 
  mutate(prop = cumsum(failed)) |> 
  ggplot()+
  geom_line(aes(x = n, y = prop, colour = as.factor(alpha)), size = 1)+
  # geom_line(aes(x = n, y =  prop ), data = p_vals_tost_break_small_alpha_df, size = 1, colour = "skyblue")+
  # geom_line(aes(x = n, y = 1 - prop,  colour = alpha), size = 1)+
  # geom_line(aes(x = n, y = 1 - prop), data = p_vals_tost_break_small_alpha_df, size = 1, colour = "deepskyblue4")+
  scale_x_log10("N")+
  scale_y_continuous("Percentage of Failed Tests (%)")+
  scale_color_discrete("Alpha Level")+
  ggtitle("Sequential Testing - False Posities at Various Alpha Levels")


# ggsave(filename = here::here("images", "ch2_seq_t_no_rope.png"), width = 10, height = 8, dpi = 360)
```


```{r}
seq_t_test_many_alphas_rope |> 
  na.omit() |> 
  ggplot(aes(x = as.integer(n), y = mean_diff, colour = as.factor(alpha), group = alpha))+
  geom_point(size = 1, alpha = .5)+
  geom_smooth(size = 1, se = F)+
  scale_x_log10("N")+
  scale_y_continuous("Mean Difference", limits = c(0,2))+
  ggtitle("Mean Difference from Sequential t-test with Rope at 0.5 Cohen's d")+
  scale_color_discrete("Alpha Level")

seq_t_test_many_alphas_rope_1 |> 
  na.omit() |> 
  ggplot(aes(x = as.integer(n), y = mean_diff, colour = as.factor(alpha), group = alpha))+
  geom_point(size = 1)+
  geom_smooth(size = 1, se = F)+
  scale_x_log10("N")+
  scale_y_continuous("Mean Difference", limits = c(0,2))+
  ggtitle("Mean Difference from Sequential t-test with Rope at 1 Cohen's d")+
  scale_color_discrete("Alpha Level")
```

```{r}
seq_t_test_many_alphas_rope_df |> 
  na.omit() |> 
  ggplot(aes(x = as.integer(n), y = prop, colour = as.factor(alpha), group = alpha))+
  geom_line(size = 1)+
  scale_x_log10("N")+
  scale_y_continuous("False Positives", limits = 0:1)+
  ggtitle("False Positives from Sequential t-test with Rope at 0.5 Cohen's d")+
  scale_color_discrete("Alpha Level")

# ggsave(filename = here::here("images", "ch2_seq_t_5_rope.png"), width = 10, height = 8, dpi = 360)

seq_t_test_many_alphas_rope_1_df |> 
  na.omit() |> 
  ggplot(aes(x = as.integer(n), y = prop, colour = as.factor(alpha), group = alpha))+
  geom_line(size = 1)+
  scale_x_log10("N")+
  scale_y_continuous("False Positives", limits = 0:1)+
  ggtitle("False Positives from Sequential t-test with Rope at 1 Cohen's d")+
  scale_color_discrete("Alpha Level")
```

```{r}

seq_t_test_many_alphas_rope_m |> 
  na.omit() |> 
  ggplot(aes(x = as.integer(n), y = mean_diff, colour = as.factor(margin), group = margin))+
  geom_point(size = 1)+
  geom_smooth(size = 1, se = F)+
  scale_x_log10("N")+
  scale_y_continuous("Mean Difference", limits = c(0,2))+
  geom_hline(aes(yintercept = margin, colour = as.factor(margin)))+
  ggtitle("Mean Difference from Sequential t-test with Alpha at 0.05, at various ROPE margins")+
  scale_color_discrete("ROPE Margins")

# ggsave(filename = here::here("images", "ch2_seq_t_many_ropes_mean.png"), width = 10, height = 8, dpi = 360)

seq_t_test_many_alphas_rope_m_df |> 
  na.omit() |> 
  ggplot(aes(x = as.integer(n), y = prop, colour = as.factor(margin), group = margin))+
  geom_line(size = 1)+
  scale_x_log10("N")+
  scale_y_continuous("False Positives", limits = 0:1)+
  ggtitle("False Positives from Sequential t-test with alpha of 0.05, at various ROPE margins")+
  scale_color_discrete("ROPE Margins")

# ggsave(filename = here::here("images", "ch2_seq_t_many_ropes_fp.png"), width = 10, height = 8, dpi = 360)

```



```{r}
p_vals_tost_break_one_sample_df |> 
  ggplot()+
  geom_line(aes(x = n, y =  prop ), size = 1, colour = "lightgrey")+
  # geom_line(aes(x = n, y =  prop ), data = p_vals_tost_break_small_alpha_df, size = 1, colour = "skyblue")+
  geom_line(aes(x = n, y = 1 - prop), size = 1, colour = "black")+
  # geom_line(aes(x = n, y = 1 - prop), data = p_vals_tost_break_small_alpha_df, size = 1, colour = "deepskyblue4")+
  scale_x_log10("N")+
  scale_y_continuous("Proportation of Decisions")
```


```{r}
p_vals_tost_break_logn_df |> 
  ggplot()+
  geom_line(aes(x = n, y = prop ), size = 1, colour = "black")+
  geom_line(aes(x = n, y = 1 - prop), size = 1, colour = "lightgrey")+
  scale_x_log10("N")+
  scale_y_continuous("Proportation of Decisions")+
  theme_minimal()
```

```{r, fig.height=8}
p_vals_tost_no_break_df |> 
  ggplot()+
  geom_ribbon(aes(x= n, ymin = mn - (sd/2), ymax = mn + (sd/2)), alpha = .4, fill = "lightblue")+
  geom_point(aes(x = n, y = mn), size = 1.5, alpha = .5, colour = "darkblue")+
  scale_x_continuous("Sample Size")+
  scale_y_continuous("Mean p-values", limits = c(.3, .7))+
  ggtitle("Mean p-value of 1000 simulations of t-test when Null is True, at various sample sizes")+
  # coord_cartesian(expand = F)+
  theme_minimal()
```